"""Report generator — outputs compliance findings in rich, JSON, or markdown."""

import json
from pathlib import Path
from typing import Any

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich import box
from rich.text import Text

console = Console()

RISK_COLOR = {"HIGH": "red", "MEDIUM": "yellow", "LOW": "green"}
RISK_EMOJI = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}


class Reporter:
    def __init__(self, results: dict[str, Any], base_path: Path):
        self.results = results
        self.base_path = base_path

    def render(self, fmt: str = "rich", output_file: str = "compliance_report.md"):
        if fmt == "rich":
            self._render_rich()
            self._save_markdown(output_file)
            console.print(f"\n[dim]Report saved to: {output_file}[/dim]")
        elif fmt == "json":
            output = output_file.replace(".md", ".json")
            Path(output).write_text(json.dumps(self.results, indent=2))
            console.print(f"[green]JSON report saved to: {output}[/green]")
        elif fmt == "markdown":
            self._save_markdown(output_file)
            console.print(f"[green]Markdown report saved to: {output_file}[/green]")

    def quick_summary(self):
        s = self.results["summary"]
        console.print(Panel(
            f"[bold]Files scanned:[/bold] {s['files_scanned']}\n"
            f"[red]HIGH[/red]: {s['high']}  "
            f"[yellow]MEDIUM[/yellow]: {s['medium']}  "
            f"[green]LOW[/green]: {s['low']}  "
            f"[dim]Total findings: {s['total']}[/dim]",
            title="[bold blue]Compliance Summary[/bold blue]",
            border_style="blue",
        ))

    def _render_rich(self):
        s = self.results["summary"]

        console.print(Panel(
            f"[bold]Project:[/bold] {self.base_path.name}\n"
            f"[bold]Files scanned:[/bold] {s['files_scanned']}\n"
            f"[red bold]HIGH risk:[/red bold] {s['high']}   "
            f"[yellow bold]MEDIUM:[/yellow bold] {s['medium']}   "
            f"[green bold]LOW:[/green bold] {s['low']}   "
            f"[dim]Total: {s['total']}[/dim]",
            title="[bold blue] AI Compliance Scanner Report [/bold blue]",
            border_style="blue",
            box=box.ROUNDED,
        ))

        for category, key in [("GDPR", "gdpr"), ("EU AI Act", "ai_act"), ("OWASP Top 10", "owasp")]:
            findings = self.results.get(key, [])
            if not findings:
                console.print(f"\n[green]✓ No {category} issues found.[/green]")
                continue

            table = Table(
                title=f"{category} Findings",
                box=box.SIMPLE_HEAD,
                show_lines=True,
                title_style="bold",
            )
            table.add_column("Risk", style="bold", width=8)
            table.add_column("Rule ID", style="dim", width=12)
            table.add_column("Title", width=32)
            table.add_column("Recommendation", width=50)

            for f in sorted(findings, key=lambda x: ["HIGH", "MEDIUM", "LOW"].index(x["risk"])):
                color = RISK_COLOR[f["risk"]]
                table.add_row(
                    Text(f"{RISK_EMOJI[f['risk']]} {f['risk']}", style=color),
                    f["rule_id"],
                    f["title"],
                    f["recommendation"],
                )

            console.print()
            console.print(table)

    def _save_markdown(self, output_file: str):
        s = self.results["summary"]
        lines = [
            "# AI Compliance Scanner Report",
            f"\n**Project:** `{self.base_path.name}`  ",
            f"**Files scanned:** {s['files_scanned']}  ",
            f"**Total findings:** {s['total']} — 🔴 HIGH: {s['high']} | 🟡 MEDIUM: {s['medium']} | 🟢 LOW: {s['low']}",
            "\n---\n",
        ]

        for category, key in [("GDPR", "gdpr"), ("EU AI Act", "ai_act"), ("OWASP Top 10", "owasp")]:
            findings = self.results.get(key, [])
            lines.append(f"## {category} Findings\n")
            if not findings:
                lines.append("✅ No issues found.\n")
                continue

            for f in sorted(findings, key=lambda x: ["HIGH", "MEDIUM", "LOW"].index(x["risk"])):
                lines.append(f"### {RISK_EMOJI[f['risk']]} [{f['risk']}] {f['title']} `{f['rule_id']}`")
                lines.append(f"\n**Description:** {f['description']}  ")
                lines.append(f"**Recommendation:** {f['recommendation']}")
                if f.get("file"):
                    lines.append(f"  \n**File:** `{f['file']}`")
                lines.append("\n")

        lines.append("---\n_Generated by [AI Compliance Scanner](https://github.com/ddugi/ai-compliance-scanner) by DUGI_\n")
        Path(output_file).write_text("\n".join(lines))
